apiVersion: helm.cattle.io/v1
kind: HelmChartConfig
metadata:
  name: traefik-close-secure-port-config
  namespace: kube-system
spec:
  valuesContent: |-
    ports:
      websecure:
        expose: false
