s3:
  endpointUrl: https://storage.yandexcloud.net
  secretName: s3-credentials
  accessKeyKey: ACCESS_KEY_ID
  secretKeyKey: ACCESS_SECRET_KEY
cnpg:
  clusterName: liquid-db
  backup:
    enable: true
    schedule: "0 0 0 * * *"
    destinationPath: "s3://liquid-code/backup-hexcore"
  recovery:
    enable: true
    oldClusterName: liquid-db
    sourcePath: "s3://liquid-code/backup"