apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-backend-deployment
  labels:
    app: {{ .Release.Name }}-backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Release.Name }}-backend
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}-backend
    spec:
      containers:
      - name: {{ .Release.Name }}-backend
        image: ghcr.io/nullptroma/liquid-backend:1.0.0
        imagePullPolicy: Always
        ports:
          - containerPort: 8080
        env:
        - name: S3_ACCESS_KEY
          valueFrom:
            secretKeyRef:
              name: {{ required "secretname!" .Values.s3.secretName | quote }}
              key: {{ required "acces-key-key!" .Values.s3.accessKeyKey | quote }}
        - name: S3_SECRET_KEY
          valueFrom:
            secretKeyRef:
              name: {{ .Values.s3.secretName | quote }}
              key: {{ required "secret-key-key!" .Values.s3.secretKeyKey | quote }}
        - name: PG_URI
          valueFrom:
            secretKeyRef:
              name: {{ required "Cluster name required" .Values.cnpg.clusterName }}-app
              key: uri
        envFrom:
          - secretRef:
              name: {{ required "" .Values.jwt.secretName }}

      imagePullSecrets:
        - name: github-registry
