apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-backend-deployment
  labels:
    app: {{ .Release.Name }}-backend
spec:
  replicas: 3
  selector:
    matchLabels:
      app: {{ .Release.Name }}-backend
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}-backend
    spec:
      containers:
        - name: {{ .Release.Name }}-backend
          image: ghcr.io/nullptroma/liquid-backend:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
          env:
            - name: S3_ENDPOINT
              value: {{ required "s3 endpoint!" .Values.s3.endpointUrl | quote }}
            - name: S3_PRIVATE_BUCKET
              value: {{ required "privateBucket!" .Values.s3.privateBucket | quote }}
            - name: S3_PUBLIC_BUCKET
              value: {{ required "publicBucket!" .Values.s3.publicBucket | quote }}
            - name: S3_ACCESS_KEY
              valueFrom:
                secretKeyRef:
                  name: {{ required "secretname!" .Values.s3.secretName | quote }}
                  key: {{ required "acces-key-key!" .Values.s3.accessKeyKey | quote }}
            - name: S3_SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.s3.secretName | quote }}
                  key: {{ required "secret-key-key!" .Values.s3.secretKeyKey | quote }}
            - name: PG_URI
              valueFrom:
                secretKeyRef:
                  name: {{ required "Cluster creds secret required!" .Values.database.secretName }}
                  key: uri
          envFrom:
            - secretRef:
                name: {{ required "" .Values.jwt.secretName }}

      imagePullSecrets:
        - name: github-registry
