apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: {{ .Release.Name }}-certificate-issuer
spec:
  acme:
    {{ if .Values.staging }}
    server: https://acme-staging-v02.api.letsencrypt.org/directory
    {{ else }}
    server: https://acme-v02.api.letsencrypt.org/directory
    {{ end }}
    # Email address used for ACME registration
    email: mr.pytkov@gmail.com
    # Name of a secret used to store the ACME account private key
    privateKeySecretRef:
      name: {{ .Release.Name }}-acme-private-key
    # Enable the HTTP-01 challenge provider
    solvers:
      - http01:
          ingress:
            ingressClassName: traefik